package retrofittestdrive

import org.slf4j.Logger
import org.slf4j.LoggerFactory
import retrofit2.Call


private val log: Logger = LoggerFactory.getLogger("Main")

fun main() {
    val client = buildBaselineClient(GitHubApi::class.java, "https://api.github.com/")
    val call: Call<List<Repo>> = client.listRepos("octocat")
    val result: List<Repo>? = call.execute().body()

    result?.forEachIndexed { i, repo -> log.info("$i) $repo") }
        ?: log.error("Result was null")
}


/**
Prints:

GitHubApi.listRepos([octocat]) - 200 in 501 ms.
[main] INFO Main - 0) Repo(id=132935648, name=boysenberry-repo-1, owner={login=octocat, id=583231, node_id=MDQ6VXNlcjU4MzIzMQ==, avatar_url=https://avatars.githubusercontent.com/u/583231?v=4, gravatar_id=, url=https://api.github.com/users/octocat, html_url=https://github.com/octocat, followers_url=https://api.github.com/users/octocat/followers, following_url=https://api.github.com/users/octocat/following{/other_user}, gists_url=https://api.github.com/users/octocat/gists{/gist_id}, starred_url=https://api.github.com/users/octocat/starred{/owner}{/repo}, subscriptions_url=https://api.github.com/users/octocat/subscriptions, organizations_url=https://api.github.com/users/octocat/orgs, repos_url=https://api.github.com/users/octocat/repos, events_url=https://api.github.com/users/octocat/events{/privacy}, received_events_url=https://api.github.com/users/octocat/received_events, type=User, site_admin=false})
[main] INFO Main - 1) Repo(id=18221276, name=git-consortium, owner={login=octocat, id=583231, node_id=MDQ6VXNlcjU4MzIzMQ==, avatar_url=https://avatars.githubusercontent.com/u/583231?v=4, gravatar_id=, url=https://api.github.com/users/octocat, html_url=https://github.com/octocat, followers_url=https://api.github.com/users/octocat/followers, following_url=https://api.github.com/users/octocat/following{/other_user}, gists_url=https://api.github.com/users/octocat/gists{/gist_id}, starred_url=https://api.github.com/users/octocat/starred{/owner}{/repo}, subscriptions_url=https://api.github.com/users/octocat/subscriptions, organizations_url=https://api.github.com/users/octocat/orgs, repos_url=https://api.github.com/users/octocat/repos, events_url=https://api.github.com/users/octocat/events{/privacy}, received_events_url=https://api.github.com/users/octocat/received_events, type=User, site_admin=false})
[main] INFO Main - 2) Repo(id=20978623, name=hello-worId, owner={login=octocat, id=583231, node_id=MDQ6VXNlcjU4MzIzMQ==, avatar_url=https://avatars.githubusercontent.com/u/583231?v=4, gravatar_id=, url=https://api.github.com/users/octocat, html_url=https://github.com/octocat, followers_url=https://api.github.com/users/octocat/followers, following_url=https://api.github.com/users/octocat/following{/other_user}, gists_url=https://api.github.com/users/octocat/gists{/gist_id}, starred_url=https://api.github.com/users/octocat/starred{/owner}{/repo}, subscriptions_url=https://api.github.com/users/octocat/subscriptions, organizations_url=https://api.github.com/users/octocat/orgs, repos_url=https://api.github.com/users/octocat/repos, events_url=https://api.github.com/users/octocat/events{/privacy}, received_events_url=https://api.github.com/users/octocat/received_events, type=User, site_admin=false})
[main] INFO Main - 3) Repo(id=1296269, name=Hello-World, owner={login=octocat, id=583231, node_id=MDQ6VXNlcjU4MzIzMQ==, avatar_url=https://avatars.githubusercontent.com/u/583231?v=4, gravatar_id=, url=https://api.github.com/users/octocat, html_url=https://github.com/octocat, followers_url=https://api.github.com/users/octocat/followers, following_url=https://api.github.com/users/octocat/following{/other_user}, gists_url=https://api.github.com/users/octocat/gists{/gist_id}, starred_url=https://api.github.com/users/octocat/starred{/owner}{/repo}, subscriptions_url=https://api.github.com/users/octocat/subscriptions, organizations_url=https://api.github.com/users/octocat/orgs, repos_url=https://api.github.com/users/octocat/repos, events_url=https://api.github.com/users/octocat/events{/privacy}, received_events_url=https://api.github.com/users/octocat/received_events, type=User, site_admin=false})
[main] INFO Main - 4) Repo(id=64778136, name=linguist, owner={login=octocat, id=583231, node_id=MDQ6VXNlcjU4MzIzMQ==, avatar_url=https://avatars.githubusercontent.com/u/583231?v=4, gravatar_id=, url=https://api.github.com/users/octocat, html_url=https://github.com/octocat, followers_url=https://api.github.com/users/octocat/followers, following_url=https://api.github.com/users/octocat/following{/other_user}, gists_url=https://api.github.com/users/octocat/gists{/gist_id}, starred_url=https://api.github.com/users/octocat/starred{/owner}{/repo}, subscriptions_url=https://api.github.com/users/octocat/subscriptions, organizations_url=https://api.github.com/users/octocat/orgs, repos_url=https://api.github.com/users/octocat/repos, events_url=https://api.github.com/users/octocat/events{/privacy}, received_events_url=https://api.github.com/users/octocat/received_events, type=User, site_admin=false})
[main] INFO Main - 5) Repo(id=17881631, name=octocat.github.io, owner={login=octocat, id=583231, node_id=MDQ6VXNlcjU4MzIzMQ==, avatar_url=https://avatars.githubusercontent.com/u/583231?v=4, gravatar_id=, url=https://api.github.com/users/octocat, html_url=https://github.com/octocat, followers_url=https://api.github.com/users/octocat/followers, following_url=https://api.github.com/users/octocat/following{/other_user}, gists_url=https://api.github.com/users/octocat/gists{/gist_id}, starred_url=https://api.github.com/users/octocat/starred{/owner}{/repo}, subscriptions_url=https://api.github.com/users/octocat/subscriptions, organizations_url=https://api.github.com/users/octocat/orgs, repos_url=https://api.github.com/users/octocat/repos, events_url=https://api.github.com/users/octocat/events{/privacy}, received_events_url=https://api.github.com/users/octocat/received_events, type=User, site_admin=false})
[main] INFO Main - 6) Repo(id=1300192, name=Spoon-Knife, owner={login=octocat, id=583231, node_id=MDQ6VXNlcjU4MzIzMQ==, avatar_url=https://avatars.githubusercontent.com/u/583231?v=4, gravatar_id=, url=https://api.github.com/users/octocat, html_url=https://github.com/octocat, followers_url=https://api.github.com/users/octocat/followers, following_url=https://api.github.com/users/octocat/following{/other_user}, gists_url=https://api.github.com/users/octocat/gists{/gist_id}, starred_url=https://api.github.com/users/octocat/starred{/owner}{/repo}, subscriptions_url=https://api.github.com/users/octocat/subscriptions, organizations_url=https://api.github.com/users/octocat/orgs, repos_url=https://api.github.com/users/octocat/repos, events_url=https://api.github.com/users/octocat/events{/privacy}, received_events_url=https://api.github.com/users/octocat/received_events, type=User, site_admin=false})
[main] INFO Main - 7) Repo(id=56271164, name=test-repo1, owner={login=octocat, id=583231, node_id=MDQ6VXNlcjU4MzIzMQ==, avatar_url=https://avatars.githubusercontent.com/u/583231?v=4, gravatar_id=, url=https://api.github.com/users/octocat, html_url=https://github.com/octocat, followers_url=https://api.github.com/users/octocat/followers, following_url=https://api.github.com/users/octocat/following{/other_user}, gists_url=https://api.github.com/users/octocat/gists{/gist_id}, starred_url=https://api.github.com/users/octocat/starred{/owner}{/repo}, subscriptions_url=https://api.github.com/users/octocat/subscriptions, organizations_url=https://api.github.com/users/octocat/orgs, repos_url=https://api.github.com/users/octocat/repos, events_url=https://api.github.com/users/octocat/events{/privacy}, received_events_url=https://api.github.com/users/octocat/received_events, type=User, site_admin=false})
 */